#!/usr/bin/env node
// Writes packages/shared/src/abis/generated.ts from Foundry's build output.
// Run `forge build` in contracts/ first. `--check` fails if the committed file is stale (used in CI).
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");
const target = join(root, "packages", "shared", "src", "abis", "generated.ts");

// [exported name, source file, contract name, required]
const ABIS = [
  ["hunchBookFactoryAbi", "IHunchBookFactory.sol", "IHunchBookFactory", true],
  ["marketAbi", "IMarket.sol", "IMarket", true],
  ["collateralVaultAbi", "ICollateralVault.sol", "ICollateralVault", true],
  ["outcomeTokenAbi", "IOutcomeToken.sol", "IOutcomeToken", true],
  ["resolverAbi", "IResolver.sol", "IResolver", true],
  ["graduatorAbi", "IGraduator.sol", "IGraduator", true],
  ["hunchRouterAbi", "IHunchRouter.sol", "IHunchRouter", true],
  ["templateParamsCodecAbi", "ITemplates.sol", "ITemplateParamsCodec", true],
  ["testUsdcAbi", "TestUSDC.sol", "TestUSDC", false],
  ["perplExchangeAbi", "IPerplExchange.sol", "IPerplExchange", false],
  ["chainlinkAggregatorAbi", "IChainlinkAggregator.sol", "IChainlinkAggregator", false],
  ["kuruOrderBookAbi", "IKuruOrderBook.sol", "IKuruOrderBook", false],
  ["kuruMarginAccountAbi", "IKuruMarginAccount.sol", "IKuruMarginAccount", false],
  ["kuruRouterAbi", "IKuruRouter.sol", "IKuruRouter", false],
];

const parts = [
  "// Generated by scripts/gen-abis.mjs from contracts/out. Do not edit by hand.",
  "// Regenerate: (cd contracts && forge build) && pnpm abis",
  "",
];
for (const [name, file, contract, required] of ABIS) {
  const path = join(out, file, `${contract}.json`);
  if (!existsSync(path)) {
    if (required) {
      console.error(`missing ${path}: run \`forge build\` in contracts/ first`);
      process.exit(1);
    }
    continue;
  }
  const { abi } = JSON.parse(readFileSync(path, "utf8"));
  parts.push(`export const ${name} = ${JSON.stringify(abi, null, 2)} as const;`, "");
}
const next = parts.join("\n");

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== next) {
    console.error("packages/shared/src/abis/generated.ts is stale: run `pnpm abis` and commit the result");
    process.exit(1);
  }
  console.log("ABIs are up to date.");
} else {
  writeFileSync(target, next);
  console.log(`wrote ${target}`);
}
